### ISSUE TITLE
Adjust permission for external contributors

### ISSUE THREAD

**Issue by fdiblen** [ci-for-science/self-hosted-runners#12]
As running the workflow on a custom server can be very expensive, we want to limit this to external contributors.

One option is to run CI for only a protected branch.
See 
https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions
https://help.github.com/en/github/administering-a-repository/configuring-protected-branches

**Comment by HannoSpreeuw** [comment]
I need access to settings to enforce those permissions, which I don't currently have.
So the settings tab is missing - for me - from the main page of the repo.

**Comment by felipeZ** [comment]
@HannoSpreeuw  I have granted you admin access :)

**Comment by HannoSpreeuw** [comment]
Since CI is performed before every merge of a pull request, I guess we have to **configure the CI workflow such that it is limited to certain users or with other restrictions**. But I don't know if that's possible.

I don't see how you can configure protected branches or enable branch restrictions such that CI is only performed with certain conditions. CI does not seem to be controlled at the level of the branches.
So I don't think CI configuration is covered by the two links above (from the OP).

**Comment by felipeZ** [comment]
@HannoSpreeuw  You can always tell GitHub to use only certain branches  by adding to the yaml file something like:
```yaml
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```
You  can also use and [if statement]( https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif) to run a job if a condition is met.
